# Generated by Django 3.2 on 2022-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Feature', 'Feature'), ('Sale', 'Sale')], default='', max_length=10, verbose_name='Flag'),
            preserve_default=False,
        ),
    ]
